apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: amira-backend-hpa
  namespace: amira
  labels:
    app: amira-backend
    component: autoscaler
  annotations:
    kubernetes.io/description: "Autoscaler for Amira Wellness Backend API Services"
    kubernetes.io/change-cause: "Initial autoscaler configuration"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amira-backend
  minReplicas: 2
  maxReplicas: 20
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300  # 5 minutes cooldown
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes cooldown
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75