apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: amira
  labels:
    app: amira-backend
    component: secrets
  annotations:
    kubernetes.io/change-cause: "Initial secrets configuration"
    description: "Sensitive configuration for Amira Wellness backend services"
type: Opaque
data:
  # Authentication secrets
  # Values must be base64 encoded in the actual implementation
  # Example: echo -n "your-secret-value" | base64
  SECRET_KEY: base64_encoded_secret_key_for_jwt_signing
  ADMIN_EMAIL: base64_encoded_admin_email
  ADMIN_PASSWORD: base64_encoded_admin_password

  # Database credentials
  POSTGRES_USER: base64_encoded_database_username
  POSTGRES_PASSWORD: base64_encoded_database_password

  # AWS credentials for S3 access and encryption
  AWS_ACCESS_KEY_ID: base64_encoded_aws_access_key
  AWS_SECRET_ACCESS_KEY: base64_encoded_aws_secret_key
  ENCRYPTION_KEY_ID: base64_encoded_kms_key_id

  # Encryption keys
  MASTER_ENCRYPTION_KEY: base64_encoded_master_encryption_key

  # Monitoring and error tracking
  SENTRY_DSN: base64_encoded_sentry_dsn

  # Notification services
  FIREBASE_CREDENTIALS: base64_encoded_firebase_service_account_json
  SMTP_USER: base64_encoded_smtp_username
  SMTP_PASSWORD: base64_encoded_smtp_password