disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - identifier_name
  - todo
  - function_parameter_count
  - nesting

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - force_unwrapping
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - private_outlet
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - file_header
  - implicit_return
  - unused_import
  - unused_declaration
  - unowned_variable_capture
  - first_where
  - last_where
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - contains_over_range_nil_comparison
  - redundant_type_annotation
  - convenience_type
  - toggle_bool
  - fallthrough
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - identical_operands
  - legacy_multiple
  - legacy_random
  - no_extension_access_modifier
  - prefer_self_type_over_type_of_self
  - redundant_objc_attribute
  - redundant_set_access_control
  - redundant_void_return
  - static_operator
  - unavailable_function
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  - AmiraWellness

excluded:
  - Pods
  - AmiraWellnessTests
  - AmiraWellnessUITests
  - fastlane
  - vendor
  - "*.generated.swift"

analyzer_rules:
  - unused_declaration
  - unused_import

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 250
  error: 350

cyclomatic_complexity:
  warning: 10
  error: 15

large_tuple:
  warning: 3
  error: 4

force_cast: warning
force_try: warning
force_unwrapping: warning
implicitly_unwrapped_optional: warning

vertical_whitespace:
  max_empty_lines: 2

trailing_comma:
  mandatory_comma: true

private_outlet:
  allow_private_set: true

file_header:
  required_pattern: |
    //
    //  \w+\.swift
    //  AmiraWellness
    //
    //  Created by .+ on \d{1,2}/\d{1,2}/\d{2,4}\.
    //  Copyright © \d{4} Amira Wellness\. All rights reserved\.
    //

custom_rules:
  empty_first_line:
    name: "Empty First Line"
    regex: "^(?!\\s*$).+"
    match_kinds:
      - comment
    message: "There should be an empty line after the file header comment"
    severity: warning
  comments_space:
    name: "Comment Space"
    regex: "^\\s*//\\w"
    match_kinds:
      - comment
    message: "There should be a space after //"
    severity: warning
  empty_line_after_super:
    name: "Empty Line After Super"
    regex: "\\}\\n\\s*override"
    message: "There should be an empty line after super"
    severity: warning
  unnecessary_type:
    name: "Unnecessary Type"
    regex: "let\\s+.+?\\s*:\\s*[a-zA-Z][a-zA-Z0-9]*\\s*=\\s*[a-zA-Z][a-zA-Z0-9]*\\([^)]*\\)"
    message: "Type definition not needed"
    severity: warning
  empty_line_after_guard:
    name: "Empty Line After Guard"
    regex: "^\\s*guard\\s+.+\\s+else\\s+\\{\\s*\\n\\s*return\\s.+\\s*\\n\\s*\\}\\n(?!\\s*$)"
    message: "There should be an empty line after a guard statement"
    severity: warning

reporter: "xcode"